# Generated by Django 2.2.11 on 2020-05-19 20:51

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSpecificFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('color', colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'])),
                ('grid_position_x', models.IntegerField()),
                ('grid_position_y', models.IntegerField()),
                ('match_none_charge', models.BooleanField(default=False)),
                ('match_none_discharge', models.BooleanField(default=False)),
                ('charge_constant_rate_min', models.FloatField()),
                ('charge_end_rate_min', models.FloatField()),
                ('charge_end_rate_prev_min', models.FloatField()),
                ('charge_end_voltage_min', models.FloatField()),
                ('charge_end_voltage_prev_min', models.FloatField()),
                ('charge_constant_rate_max', models.FloatField()),
                ('charge_end_rate_max', models.FloatField()),
                ('charge_end_rate_prev_max', models.FloatField()),
                ('charge_end_voltage_max', models.FloatField()),
                ('charge_end_voltage_prev_max', models.FloatField()),
                ('discharge_constant_rate_min', models.FloatField()),
                ('discharge_end_rate_min', models.FloatField()),
                ('discharge_end_rate_prev_min', models.FloatField()),
                ('discharge_end_voltage_min', models.FloatField()),
                ('discharge_end_voltage_prev_min', models.FloatField()),
                ('discharge_constant_rate_max', models.FloatField()),
                ('discharge_end_rate_max', models.FloatField()),
                ('discharge_end_rate_prev_max', models.FloatField()),
                ('discharge_end_voltage_max', models.FloatField()),
                ('discharge_end_voltage_prev_max', models.FloatField()),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cell_database.Dataset')),
                ('wet_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cell_database.WetCell')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetSpecificCellName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cell_database.Dataset')),
                ('wet_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cell_database.WetCell')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datasetspecificfilters',
            constraint=models.UniqueConstraint(fields=('dataset', 'wet_cell', 'name'), name='unique_dataset_cell_filter_name'),
        ),
        migrations.AddConstraint(
            model_name='datasetspecificcellname',
            constraint=models.UniqueConstraint(fields=('dataset', 'name'), name='unique_dataset_specific_name'),
        ),
    ]
