# Generated by Django 2.2.11 on 2020-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0002_auto_20200610_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratiocomponent',
            name='overridden_component_type',
            field=models.CharField(blank=True, choices=[('sa', 'salt'), ('ad', 'additive'), ('so', 'solvent'), ('am', 'active_material'), ('co', 'conductive_additive'), ('bi', 'binder'), ('se', 'separator_material')], max_length=2),
        ),
    ]
