# Generated by Django 2.2.11 on 2020-05-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0002_auto_20200519_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='charge_constant_rate_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_prev_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_prev_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='discharge_constant_rate_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_prev_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_prev_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
        migrations.AddField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_type',
            field=models.CharField(blank=True, choices=[('any', 'match any'), ('int', 'match interval')], max_length=3),
        ),
    ]
