# Generated by Django 2.2.11 on 2020-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0003_auto_20200519_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='charge_constant_rate_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_prev_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_prev_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='discharge_constant_rate_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_prev_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_prev_type',
        ),
        migrations.RemoveField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_type',
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_constant_rate_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_constant_rate_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_prev_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_rate_prev_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_prev_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='charge_end_voltage_prev_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_constant_rate_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_constant_rate_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_prev_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_rate_prev_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_prev_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='discharge_end_voltage_prev_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='grid_position_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='datasetspecificfilters',
            name='grid_position_y',
            field=models.IntegerField(default=1),
        ),
    ]
