# Generated by Django 2.2.11 on 2020-05-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0004_auto_20200520_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetspecificcellname',
            name='grid_position_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datasetspecificcellname',
            name='grid_position_y',
            field=models.IntegerField(default=1),
        ),
    ]
