# Generated by Django 2.2.12 on 2020-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0005_mycache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellExtraMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('ocv', models.FloatField(blank=True, help_text='volts', null=True)),
                ('ac_ir', models.FloatField(blank=True, help_text='milliohms', null=True)),
                ('weight', models.FloatField(blank=True, help_text='grams', null=True)),
                ('thickness', models.FloatField(blank=True, help_text='millimeters', null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cellextrameasurements',
            constraint=models.UniqueConstraint(fields=('cell_id', 'notes'), name='unique_cell_id_notes'),
        ),
    ]
