# Generated by Django 2.2.11 on 2020-05-26 15:50

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell_database', '0005_auto_20200525_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetspecificcellname',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'], default='#000000'),
            preserve_default=False,
        ),
    ]
