# Generated by Django 2.2.6 on 2019-10-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratiocomponent',
            old_name='compound_type',
            new_name='component_type',
        ),
        migrations.AlterField(
            model_name='component',
            name='coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WetCellDatabase.Coating'),
        ),
        migrations.AlterField(
            model_name='component',
            name='core_shell',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='natural',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='particle_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='preparation_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='single_crystal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='smiles',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='turbostratic_misalignment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='vendor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
