# Generated by Django 2.2.6 on 2019-10-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0002_auto_20191022_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='vendor',
        ),
        migrations.AddField(
            model_name='lotinfo',
            name='vendor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
