# Generated by Django 2.2.6 on 2019-10-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0003_auto_20191023_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='coating',
        ),
        migrations.CreateModel(
            name='CoatingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WetCellDatabase.Coating')),
                ('lot_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WetCellDatabase.LotInfo')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='coating_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WetCellDatabase.CoatingLot'),
        ),
    ]
