# Generated by Django 2.2.6 on 2019-10-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0004_auto_20191023_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotinfo',
            name='known_lot',
        ),
    ]
