# Generated by Django 2.2.6 on 2019-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0006_auto_20191031_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratiocomponent',
            name='composite',
        ),
        migrations.AddField(
            model_name='composite',
            name='components',
            field=models.ManyToManyField(to='WetCellDatabase.RatioComponent'),
        ),
    ]
