# Generated by Django 2.2.6 on 2019-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0007_auto_20191031_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrodematerialstochiometry',
            name='electrode_material',
        ),
        migrations.AddField(
            model_name='component',
            name='stochiometry',
            field=models.ManyToManyField(to='WetCellDatabase.ElectrodeMaterialStochiometry'),
        ),
    ]
