# Generated by Django 2.2.6 on 2019-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0008_auto_20191104_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(blank=True, choices=[('sa', 'salt'), ('ad', 'additive'), ('so', 'solvent'), ('am', 'active_material'), ('co', 'conductive_additive'), ('bi', 'binder'), ('se', 'separator_material')], max_length=2),
        ),
    ]
