# Generated by Django 2.2.6 on 2019-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0013_auto_20191106_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drycellgeometry',
            old_name='cell_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='drycellgeometry',
            old_name='cell_thickness',
            new_name='thickness',
        ),
        migrations.RenameField(
            model_name='drycellgeometry',
            old_name='cell_width',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='separatorgeometry',
            old_name='base_thickness',
            new_name='thickness',
        ),
        migrations.AddField(
            model_name='component',
            name='coating_lot_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='composite_type_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='natural_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='notes_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='particle_size_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='preparation_temperature_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='single_crystal_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='turbostratic_misalignment_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='composite',
            name='composite_type_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycell',
            name='anode_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycell',
            name='cathode_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycell',
            name='geometry_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycell',
            name='max_charge_voltage_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycell',
            name='separator_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycell',
            name='version_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycellgeometry',
            name='geometry_category_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycellgeometry',
            name='length_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycellgeometry',
            name='thickness_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='drycellgeometry',
            name='width_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='electrodegeometry',
            name='density_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='electrodegeometry',
            name='loading_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='electrodegeometry',
            name='thickness_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='separatorgeometry',
            name='thickness_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='separatorgeometry',
            name='width_name',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
