# Generated by Django 2.2.6 on 2019-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0014_auto_20191112_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrodematerialstochiometry',
            name='stochiometry',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
