# Generated by Django 2.2.6 on 2019-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0015_auto_20191125_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
        migrations.RemoveField(
            model_name='composite',
            name='name',
        ),
        migrations.AddField(
            model_name='component',
            name='proprietary_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='smiles_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='composite',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='composite',
            name='notes_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='composite',
            name='proprietary_name',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
