# Generated by Django 2.2.6 on 2019-11-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0016_auto_20191126_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='notes_name',
        ),
        migrations.RemoveField(
            model_name='composite',
            name='notes_name',
        ),
    ]
