# Generated by Django 2.2.6 on 2019-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0017_auto_20191126_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotinfo',
            old_name='lot_name',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='lotinfo',
            name='creator_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lotinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotinfo',
            name='date_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='lotinfo',
            name='vendor_name',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
