# Generated by Django 2.2.6 on 2019-11-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0018_auto_20191127_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='coating_lot_unknown',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='particle_size',
            field=models.FloatField(blank=True, help_text='micrometers', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='preparation_temperature',
            field=models.FloatField(blank=True, help_text='celsius', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='single_crystal',
            field=models.CharField(blank=True, choices=[('sc', 'single_crystal'), ('po', 'poly_crystal'), ('mx', 'mixed_crystal'), ('un', 'unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='turbostratic_misalignment',
            field=models.FloatField(blank=True, help_text='percent', null=True),
        ),
        migrations.AlterField(
            model_name='electrodegeometry',
            name='density',
            field=models.FloatField(blank=True, help_text='grams per cubic centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='electrodegeometry',
            name='loading',
            field=models.FloatField(blank=True, help_text='milligrams per squared centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='electrodegeometry',
            name='thickness',
            field=models.FloatField(blank=True, help_text='micrometers', null=True),
        ),
        migrations.AlterField(
            model_name='lotinfo',
            name='date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='separatorgeometry',
            name='thickness',
            field=models.FloatField(blank=True, help_text='millimeters', null=True),
        ),
        migrations.AlterField(
            model_name='separatorgeometry',
            name='width',
            field=models.FloatField(blank=True, help_text='millimeters', null=True),
        ),
    ]
