# Generated by Django 2.2.11 on 2020-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0019_auto_20191127_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drycell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drycell',
            name='max_charge_voltage',
        ),
        migrations.RemoveField(
            model_name='drycell',
            name='max_charge_voltage_name',
        ),
        migrations.RemoveField(
            model_name='drycell',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drycell',
            name='version',
        ),
        migrations.RemoveField(
            model_name='drycell',
            name='version_name',
        ),
        migrations.AddField(
            model_name='drycell',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='drycell',
            name='proprietary_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='drycellgeometry',
            name='length',
            field=models.FloatField(blank=True, help_text='Millimeters (mm)', null=True),
        ),
        migrations.AlterField(
            model_name='drycellgeometry',
            name='thickness',
            field=models.FloatField(blank=True, help_text='Millimeters (mm)', null=True),
        ),
        migrations.AlterField(
            model_name='drycellgeometry',
            name='width',
            field=models.FloatField(blank=True, help_text='Millimeters (mm)', null=True),
        ),
    ]
