# Generated by Django 2.2.11 on 2020-03-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0020_auto_20200327_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='coating_lot_unknown',
        ),
        migrations.AlterField(
            model_name='component',
            name='single_crystal',
            field=models.CharField(blank=True, choices=[('sc', 'single_crystal'), ('po', 'poly_crystal'), ('mx', 'mixed_crystal'), ('un', 'unknown_crystal')], max_length=2, null=True),
        ),
    ]
