# Generated by Django 2.2.11 on 2020-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0021_auto_20200327_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coating',
            old_name='name',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='coating',
            name='description_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coating',
            name='proprietary_name',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='single_crystal',
            field=models.CharField(blank=True, choices=[('sc', 'Single'), ('po', 'Poly'), ('mx', 'Mixed')], max_length=2, null=True),
        ),
    ]
