# Generated by Django 2.2.11 on 2020-04-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0022_auto_20200405_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='composite_type',
            field=models.CharField(blank=True, choices=[('el', 'electrolyte'), ('ed', 'electrode'), ('se', 'separator')], max_length=2),
        ),
    ]
