# Generated by Django 2.2.11 on 2020-04-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WetCellDatabase', '0023_auto_20200422_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composite',
            name='electrode_geometry',
        ),
        migrations.RemoveField(
            model_name='composite',
            name='separator_geometry',
        ),
        migrations.AddField(
            model_name='drycell',
            name='anode_geometry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anode_geometry', to='WetCellDatabase.ElectrodeGeometry'),
        ),
        migrations.AddField(
            model_name='drycell',
            name='cathode_geometry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cathode_geometry', to='WetCellDatabase.ElectrodeGeometry'),
        ),
        migrations.AddField(
            model_name='drycell',
            name='separator_geometry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WetCellDatabase.SeparatorGeometry'),
        ),
    ]
