# Generated by Django 2.2.11 on 2020-05-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filename_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimenttype',
            old_name='barcode_active',
            new_name='cell_id_active',
        ),
        migrations.RenameField(
            model_name='validmetadata',
            old_name='barcode',
            new_name='cell_id',
        ),
    ]
