# Generated by Django 2.2.6 on 2019-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neware_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodenode',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
