# Generated by Django 2.2.6 on 2019-11-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neware_parser', '0002_auto_20191022_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='discharge_curve',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='discharge_curve_maximum_voltage',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='discharge_curve_minimum_voltage',
        ),
        migrations.RemoveField(
            model_name='cyclingfile',
            name='uniform_voltages',
        ),
    ]
