# Generated by Django 2.2.6 on 2020-02-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neware_parser', '0003_auto_20191125_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='constant_current',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='constant_voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='end_current',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='end_current_prev',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='end_voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='end_voltage_prev',
            field=models.FloatField(null=True),
        ),
    ]
