# Generated by Django 2.2.6 on 2020-02-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neware_parser', '0004_auto_20200208_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCycleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField()),
                ('constant_rate', models.FloatField()),
                ('end_rate_prev', models.FloatField()),
                ('end_voltage', models.FloatField()),
                ('end_voltage_prev', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DischargeCycleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField()),
                ('constant_rate', models.FloatField()),
                ('end_rate_prev', models.FloatField()),
                ('end_voltage', models.FloatField()),
                ('end_voltage_prev', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='group',
        ),
        migrations.DeleteModel(
            name='CycleGroup',
        ),
        migrations.AddField(
            model_name='cycle',
            name='charge_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neware_parser.ChargeCycleGroup'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='discharge_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neware_parser.DischargeCycleGroup'),
        ),
    ]
