# Generated by Django 2.2.11 on 2020-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='v_c_q_t_data',
            field=models.BinaryField(max_length=1048576, null=True),
        ),
    ]
