# Generated by Django 2.2.11 on 2020-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellGlobals',
            fields=[
                ('cell_id', models.IntegerField(primary_key=True, serialize=False)),
                ('theoretical_capacity', models.FloatField(blank=True, null=True)),
                ('auto_update_capacity', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cyclegroup',
            old_name='constant_rate',
            new_name='constant_current',
        ),
        migrations.RenameField(
            model_name='cyclegroup',
            old_name='end_rate',
            new_name='end_current',
        ),
        migrations.RenameField(
            model_name='cyclegroup',
            old_name='end_rate_prev',
            new_name='end_current_prev',
        ),
    ]
