# Generated by Django 2.2.11 on 2020-05-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarcodeNode',
        ),
        migrations.RenameField(
            model_name='chargecyclegroup',
            old_name='barcode',
            new_name='cell_id',
        ),
        migrations.RenameField(
            model_name='dischargecyclegroup',
            old_name='barcode',
            new_name='cell_id',
        ),
    ]
