# Generated by Django 2.2.11 on 2020-05-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0002_auto_20200507_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('constant_rate', models.FloatField()),
                ('end_rate', models.FloatField()),
                ('end_rate_prev', models.FloatField()),
                ('end_voltage', models.FloatField()),
                ('end_voltage_prev', models.FloatField()),
                ('polarity', models.CharField(blank=True, choices=[('chg', 'CHARGE'), ('dchg', 'DISCHARGE')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='charge_group',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='discharge_group',
        ),
        migrations.DeleteModel(
            name='ChargeCycleGroup',
        ),
        migrations.DeleteModel(
            name='DischargeCycleGroup',
        ),
    ]
