# Generated by Django 2.2.11 on 2020-05-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0003_auto_20200507_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='charge_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_group', to='cycling.CycleGroup'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='discharge_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_group', to='cycling.CycleGroup'),
        ),
    ]
